<a href="https://colab.research.google.com/github/arisa-gh/pictures/blob/master/learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import sys
sys.path.append('/content/drive/My Drive/pictures/')

import importlib
import ic_module as ic
importlib.reload(ic)

# 関数実行
ic.Learning(tsnum=30, nb_epoch=50, batch_size=8, learn_schedule=0.9)


>> 学習サンプル数 :  (432, 32, 32, 3)
>> 学習開始
Epoch 1/50
43/43 [==============================] - ETA: 0s - loss: 1.1190 - accuracy: 0.3333
Epoch 00001: val_loss improved from inf to 1.09875, saving model to best.hdf5
43/43 [==============================] - 2s 57ms/step - loss: 1.1190 - accuracy: 0.3333 - val_loss: 1.0987 - val_accuracy: 0.2889
Epoch 2/50
42/43 [============================>.] - ETA: 0s - loss: 1.0995 - accuracy: 0.3631
Epoch 00002: val_loss improved from 1.09875 to 1.09766, saving model to best.hdf5
43/43 [==============================] - 2s 53ms/step - loss: 1.0993 - accuracy: 0.3626 - val_loss: 1.0977 - val_accuracy: 0.3333
Epoch 3/50
42/43 [============================>.] - ETA: 0s - loss: 1.0934 - accuracy: 0.3988
Epoch 00003: val_loss improved from 1.09766 to 1.09656, saving model to best.hdf5
43/43 [==============================] - 2s 53ms/step - loss: 1.0941 - accuracy: 0.3947 - val_loss: 1.0966 - val_accuracy: 0.3556
Epoch 4/50
42/43 [============================>

In [ ]:
import ic_module as ic
import os.path as op

while True:
    while True:
        imgname = input("\n>> 入力したい画像ファイル(「END」で終了) ： ")
        if op.isfile(imgname) or imgname == "END":
            break
        print(">> そのファイルは存在しません！")
    if imgname == "END":
        break

    # 関数実行
    ic.TestProcess(imgname)


>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/pictures/face/test
>> そのファイルは存在しません！

>> 入力したい画像ファイル(「END」で終了) ： test
>> そのファイルは存在しません！

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/pictures/face/test/image_12.jpg
>> 計算結果↓
[[0.21805383 0.7625905  0.01935566]]
>> この画像は「橋本環奈」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/pictures/face/test/image_13.jpg
>> 計算結果↓
[[0.64599144 0.3427397  0.01126882]]
>> この画像は「山下美月」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/pictures/face/test/image_14.jpg
>> 計算結果↓
[[0.219828   0.67991847 0.10025353]]
>> この画像は「橋本環奈」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/pictures/face/test/image_15.jpg
>> 計算結果↓
[[0.06837586 0.8501692  0.08145493]]
>> この画像は「橋本環奈」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/pictures/face/test/image_0.jpg
>> 計算結果↓
[[0.0241129  0.05059047 0.92529666]]
>> この画像は「白石麻衣」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/pictures/face/test/image_1.jpg
>> 計算結果↓
[[0.01919231 0.0188737  0.961